server:
  port: 8082
  servlet:
    context-path: /springboot
spring:
  datasource:
    url: jdbc:mysql://139.196.36.243:3918/cash_database?useUnicode=true&characterEncoding=utf-8&autoReconnect=true
    username: admin
    password: 42P%*FdfA323JSD%2s45
mybatis:
    mapper-locations: classpath:mapping/*.xml
logging:
  file: myapp.log
  config: classpath:logbackProd-spring.xml
  path: ./logs
  level:
    com.wjq.dao: debug