server:
  port: 8082
  servlet:
    context-path: /springboot
spring:
  datasource:
    url: jdbc:mysql://192.168.1.213/cash_database?useUnicode=true&characterEncoding=utf-8&autoReconnect=true
    username: admin
    password: admin
mybatis:
    mapper-locations: classpath:mapping/*.xml
logging:
  file: myapp.log
  config: classpath:logbackProd-spring.xml
  path: ./logs
  level:
    com.wjq.dao: debug
